// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntyonomwmtsqqhnrbwnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50eW9ub213bXRzcXFobnJid250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NTI5MDIsImV4cCI6MjA2NzQyODkwMn0.2a7L3JkJIHx2naJDx-VP3DgN0sIop3NL-i3yyHfpwcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});